@echo off
rem Batch generated by LSD
echo Processing 1 configuration files in up to 8 parallel processes...
if "%~1"=="" (set LSD_EXEC="C:\LSD\Work\Projeto\lsdNW.exe") else (set LSD_EXEC="%~1")
if "%~2"=="" (set LSD_CONFIG_PATH="C:\LSD\Work\Projeto") else (set LSD_CONFIG_PATH="%~2")
set LSD_EXEC=%LSD_EXEC:"=%
set LSD_CONFIG_PATH=%LSD_CONFIG_PATH:"=%
echo LSD executable: %LSD_EXEC%
echo Configuration path: %LSD_CONFIG_PATH%
echo Use Cenario.bat LSD_EXEC CONFIG_PATH to change defaults
start "LSD Process 1" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Cenario_0.lsd" -p -l "%LSD_CONFIG_PATH%\Cenario_0.log"
echo 1 log files being generated.
